/*
 * TransPA Public API
 *
 * # This API exposes functionality in Visma TransPA. ## Authentication The API can be tested without authentication against the mock server in the **Servers** pulldown list. To test against the actual backend you have to register a user on the *Visma Developer Portal* and request access to the API along with the required scopes. The scopes required are documented under each endpoint. For more information about *Visma Developer Portal* see <https://developer.visma.com>. <br/> <br/>  Authentication uses OAuth tokens from *Visma Connect*. Authorization is done on tenant level, so one OAuth token is needed per tenant.<br/> <br/> The scope `transpaapi:api` grants basic access to the API and is required for all routes. Additional scopes might be required and are described inside each route description. <br/> ## Details All monetary amounts are in the organizations local currency unless otherwise specified. <br/> <br/> ```[Not Ready]``` This is an endpoint where development has not completed and is therefore subject to change. 
 *
 * The version of the OpenAPI document: 0.1.21
 * Contact: utveckling.transpa@visma.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using transpa.api.generated.Client;
using transpa.api.generated.Model;

namespace transpa.api.generated.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmployeesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// [Not ready] Get an Employee
        /// </summary>
        /// <remarks>
        /// Required scope transpaapi:employees:read 
        /// </remarks>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Resource ID</param>
        /// <returns>Employee</returns>
        Employee GetEmployee(string id);

        /// <summary>
        /// [Not ready] Get an Employee
        /// </summary>
        /// <remarks>
        /// Required scope transpaapi:employees:read 
        /// </remarks>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Resource ID</param>
        /// <returns>ApiResponse of Employee</returns>
        ApiResponse<Employee> GetEmployeeWithHttpInfo(string id);
        /// <summary>
        /// [Not ready] Return a list of Employees
        /// </summary>
        /// <remarks>
        /// Returns a list of Employees  Required scope transpaapi:employees:read 
        /// </remarks>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination token used to query for the next part of a list. (optional)</param>
        /// <param name="limit">Limits the number of Employees returned. Default and maximum is 100 (optional)</param>
        /// <param name="includeInactive">Will include non active employees if set to true (optional, default to false)</param>
        /// <returns>InlineResponse2001</returns>
        InlineResponse2001 GetEmployees(string cursor = default(string), int? limit = default(int?), bool? includeInactive = default(bool?));

        /// <summary>
        /// [Not ready] Return a list of Employees
        /// </summary>
        /// <remarks>
        /// Returns a list of Employees  Required scope transpaapi:employees:read 
        /// </remarks>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination token used to query for the next part of a list. (optional)</param>
        /// <param name="limit">Limits the number of Employees returned. Default and maximum is 100 (optional)</param>
        /// <param name="includeInactive">Will include non active employees if set to true (optional, default to false)</param>
        /// <returns>ApiResponse of InlineResponse2001</returns>
        ApiResponse<InlineResponse2001> GetEmployeesWithHttpInfo(string cursor = default(string), int? limit = default(int?), bool? includeInactive = default(bool?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmployeesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// [Not ready] Get an Employee
        /// </summary>
        /// <remarks>
        /// Required scope transpaapi:employees:read 
        /// </remarks>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Resource ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Employee</returns>
        System.Threading.Tasks.Task<Employee> GetEmployeeAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// [Not ready] Get an Employee
        /// </summary>
        /// <remarks>
        /// Required scope transpaapi:employees:read 
        /// </remarks>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Resource ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Employee)</returns>
        System.Threading.Tasks.Task<ApiResponse<Employee>> GetEmployeeWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// [Not ready] Return a list of Employees
        /// </summary>
        /// <remarks>
        /// Returns a list of Employees  Required scope transpaapi:employees:read 
        /// </remarks>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination token used to query for the next part of a list. (optional)</param>
        /// <param name="limit">Limits the number of Employees returned. Default and maximum is 100 (optional)</param>
        /// <param name="includeInactive">Will include non active employees if set to true (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InlineResponse2001</returns>
        System.Threading.Tasks.Task<InlineResponse2001> GetEmployeesAsync(string cursor = default(string), int? limit = default(int?), bool? includeInactive = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// [Not ready] Return a list of Employees
        /// </summary>
        /// <remarks>
        /// Returns a list of Employees  Required scope transpaapi:employees:read 
        /// </remarks>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination token used to query for the next part of a list. (optional)</param>
        /// <param name="limit">Limits the number of Employees returned. Default and maximum is 100 (optional)</param>
        /// <param name="includeInactive">Will include non active employees if set to true (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InlineResponse2001)</returns>
        System.Threading.Tasks.Task<ApiResponse<InlineResponse2001>> GetEmployeesWithHttpInfoAsync(string cursor = default(string), int? limit = default(int?), bool? includeInactive = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmployeesApi : IEmployeesApiSync, IEmployeesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EmployeesApi : IEmployeesApi
    {
        private transpa.api.generated.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EmployeesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EmployeesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmployeesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EmployeesApi(string basePath)
        {
            this.Configuration = transpa.api.generated.Client.Configuration.MergeConfigurations(
                transpa.api.generated.Client.GlobalConfiguration.Instance,
                new transpa.api.generated.Client.Configuration { BasePath = basePath }
            );
            this.Client = new transpa.api.generated.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new transpa.api.generated.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = transpa.api.generated.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmployeesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EmployeesApi(transpa.api.generated.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = transpa.api.generated.Client.Configuration.MergeConfigurations(
                transpa.api.generated.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new transpa.api.generated.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new transpa.api.generated.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = transpa.api.generated.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmployeesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public EmployeesApi(transpa.api.generated.Client.ISynchronousClient client, transpa.api.generated.Client.IAsynchronousClient asyncClient, transpa.api.generated.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = transpa.api.generated.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public transpa.api.generated.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public transpa.api.generated.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public transpa.api.generated.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public transpa.api.generated.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// [Not ready] Get an Employee Required scope transpaapi:employees:read 
        /// </summary>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Resource ID</param>
        /// <returns>Employee</returns>
        public Employee GetEmployee(string id)
        {
            transpa.api.generated.Client.ApiResponse<Employee> localVarResponse = GetEmployeeWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [Not ready] Get an Employee Required scope transpaapi:employees:read 
        /// </summary>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Resource ID</param>
        /// <returns>ApiResponse of Employee</returns>
        public transpa.api.generated.Client.ApiResponse<Employee> GetEmployeeWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new transpa.api.generated.Client.ApiException(400, "Missing required parameter 'id' when calling EmployeesApi->GetEmployee");

            transpa.api.generated.Client.RequestOptions localVarRequestOptions = new transpa.api.generated.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = transpa.api.generated.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = transpa.api.generated.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", transpa.api.generated.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (visma_connect) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Employee>("/v1/employees/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetEmployee", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// [Not ready] Get an Employee Required scope transpaapi:employees:read 
        /// </summary>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Resource ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Employee</returns>
        public async System.Threading.Tasks.Task<Employee> GetEmployeeAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            transpa.api.generated.Client.ApiResponse<Employee> localVarResponse = await GetEmployeeWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [Not ready] Get an Employee Required scope transpaapi:employees:read 
        /// </summary>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Resource ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Employee)</returns>
        public async System.Threading.Tasks.Task<transpa.api.generated.Client.ApiResponse<Employee>> GetEmployeeWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new transpa.api.generated.Client.ApiException(400, "Missing required parameter 'id' when calling EmployeesApi->GetEmployee");


            transpa.api.generated.Client.RequestOptions localVarRequestOptions = new transpa.api.generated.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = transpa.api.generated.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = transpa.api.generated.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", transpa.api.generated.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (visma_connect) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Employee>("/v1/employees/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetEmployee", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// [Not ready] Return a list of Employees Returns a list of Employees  Required scope transpaapi:employees:read 
        /// </summary>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination token used to query for the next part of a list. (optional)</param>
        /// <param name="limit">Limits the number of Employees returned. Default and maximum is 100 (optional)</param>
        /// <param name="includeInactive">Will include non active employees if set to true (optional, default to false)</param>
        /// <returns>InlineResponse2001</returns>
        public InlineResponse2001 GetEmployees(string cursor = default(string), int? limit = default(int?), bool? includeInactive = default(bool?))
        {
            transpa.api.generated.Client.ApiResponse<InlineResponse2001> localVarResponse = GetEmployeesWithHttpInfo(cursor, limit, includeInactive);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [Not ready] Return a list of Employees Returns a list of Employees  Required scope transpaapi:employees:read 
        /// </summary>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination token used to query for the next part of a list. (optional)</param>
        /// <param name="limit">Limits the number of Employees returned. Default and maximum is 100 (optional)</param>
        /// <param name="includeInactive">Will include non active employees if set to true (optional, default to false)</param>
        /// <returns>ApiResponse of InlineResponse2001</returns>
        public transpa.api.generated.Client.ApiResponse<InlineResponse2001> GetEmployeesWithHttpInfo(string cursor = default(string), int? limit = default(int?), bool? includeInactive = default(bool?))
        {
            transpa.api.generated.Client.RequestOptions localVarRequestOptions = new transpa.api.generated.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = transpa.api.generated.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = transpa.api.generated.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(transpa.api.generated.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(transpa.api.generated.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (includeInactive != null)
            {
                localVarRequestOptions.QueryParameters.Add(transpa.api.generated.Client.ClientUtils.ParameterToMultiMap("", "includeInactive", includeInactive));
            }

            // authentication (visma_connect) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<InlineResponse2001>("/v1/employees", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetEmployees", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// [Not ready] Return a list of Employees Returns a list of Employees  Required scope transpaapi:employees:read 
        /// </summary>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination token used to query for the next part of a list. (optional)</param>
        /// <param name="limit">Limits the number of Employees returned. Default and maximum is 100 (optional)</param>
        /// <param name="includeInactive">Will include non active employees if set to true (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of InlineResponse2001</returns>
        public async System.Threading.Tasks.Task<InlineResponse2001> GetEmployeesAsync(string cursor = default(string), int? limit = default(int?), bool? includeInactive = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            transpa.api.generated.Client.ApiResponse<InlineResponse2001> localVarResponse = await GetEmployeesWithHttpInfoAsync(cursor, limit, includeInactive, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [Not ready] Return a list of Employees Returns a list of Employees  Required scope transpaapi:employees:read 
        /// </summary>
        /// <exception cref="transpa.api.generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination token used to query for the next part of a list. (optional)</param>
        /// <param name="limit">Limits the number of Employees returned. Default and maximum is 100 (optional)</param>
        /// <param name="includeInactive">Will include non active employees if set to true (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (InlineResponse2001)</returns>
        public async System.Threading.Tasks.Task<transpa.api.generated.Client.ApiResponse<InlineResponse2001>> GetEmployeesWithHttpInfoAsync(string cursor = default(string), int? limit = default(int?), bool? includeInactive = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            transpa.api.generated.Client.RequestOptions localVarRequestOptions = new transpa.api.generated.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = transpa.api.generated.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = transpa.api.generated.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(transpa.api.generated.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(transpa.api.generated.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (includeInactive != null)
            {
                localVarRequestOptions.QueryParameters.Add(transpa.api.generated.Client.ClientUtils.ParameterToMultiMap("", "includeInactive", includeInactive));
            }

            // authentication (visma_connect) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<InlineResponse2001>("/v1/employees", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetEmployees", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
